### ISSUE TITLE
Crash in reloadfs

### ISSUE THREAD

**Issue by oscar-broman** [Zeex/samp-plugin-crashdetect#45]
The server crashes quite often when I reload a FS. It does not crash if I don't use crashdetect, or if I use the JIT plugin.
Also, reloading the FS from the console is even more crash-prone than doing it in-game.

How can I debug this further so you get some better information? It's on Windows.

```
[2015-09-20 17:31:32]   Filterscript 'gang.amx' loaded.
[2015-09-20 17:31:32] [debug] Server crashed due to an unknown error
[2015-09-20 17:31:32] [debug] Native backtrace:
[2015-09-20 17:31:32] [debug] #0 00401696 in ?? () from samp-server.exe
[2015-09-20 17:31:32] [debug] #1 00480c41 in ?? () from samp-server.exe
[2015-09-20 17:31:32] [debug] #2 004912ba in ?? () from samp-server.exe
[2015-09-20 17:31:32] [debug] #3 004912c7 in ?? () from samp-server.exe
```

**Comment by kurta999** [comment]
Good to know that this is caused by crashdetect.

Confirmed!

**Comment by Zeex** [comment]
Have you tried running the server under a debugger (e.g. Visual Studio or WinDbg)? Not sure if that would produce something useful though.

I can do this myself if you provide the AMX file for the filterscript, I've tried using some of the standard filterscripts but they didn't reproduce this crash.

**Comment by kurta999** [comment]
Not tried it in VS but you won't get this crash for first time. You need sometimes to reload fs from console around 10-13 times to crash, sometime it crash for first time. Anyway just a simple example script, but the script doesn't matter because after some time it will crash with any script.

http://www.solidfiles.com/d/024a657d41/

**Comment by oscar-broman** [comment]
Worth mentioning is this should not be confused with the issue that arise if an unfinished `HTTP` is active while reloading the FS.

**Comment by kurta999** [comment]
I think it's totally not because I don't use anywhere HTTP in my server.

**Comment by oscar-broman** [comment]
Yeah that's what I said!

**Comment by Zeex** [comment]
@oscar-broman Could you save a crash dump? (and upload it somewhere where you can later delete it in case it contains sensitive information).

Also I looked up those addresses from the stack trace in IDA, and it seems that the server crashed while trying to call some public because the AMX had been partially freed prior to that (amx->base was NULL or invalid) but I can't say which one as there's not enough info.
